version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ChangeMe@123
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongodb:/data/db
